# Generated by Django 4.1.2 on 2022-11-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='cantidad',
        ),
    ]
